export const resumesItem={
    firstName: "",
    lastName: "",
    studentid:"",
    jesiat: "",
    marriage: "",
    sarbazi: "",
    birthdayDay: "",
    birthdayMonth:"",
    birthdayYear:"",
    email: "",
    mobile: "",
    tell: "",
    country: "",
    province: "",
    city: "",
    address: "",
    social1: "",
    id1: "",
    social2: "",
    id2: "",
    social3: "",
    id3: "",
    social4: "",
    id4: "",
    language1: "",
    languageLevel1: "",
    readingLevel1: "",
    writingLevel1: "",
    listeningLevel1: "",
    speakingLevel1: "",
    languageExplain1: "",
    language2: "",
    languageLevel2: "",
    readingLevel2: "",
    writingLevel2: "",
    listeningLevel2: "",
    speakingLevel2: "",
    languageExplain2: "",
    language3: "",
    languageLevel3: "",
    readingLevel3: "",
    writingLevel3: "",
    listeningLevel3: "",
    speakingLevel3: "",
    languageExplain3: "",
    skil1: "",
    skilLevel1: "",
    skil2: "",
    skilLevel2: "",
    skil3: "",
    skilLevel3: "",
    skil4: "",
    skilLevel4: "",
    course1: "",
    institude1: "",
    date1: "",
    year1:"",
    link1: "",
    course2: "",
    institude2: "",
    date2: "",
    year2:"",
    link2: "",
    course3: "",
    institude3: "",
    date3: "",
    year3:"",
    link3: "",
   
}